version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: desafio-backend
    ports:
      - "8080:8080"     
    environment: {}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: desafio-frontend
    ports:
      - "5173:5173"     
    depends_on:
      - backend
    environment: {}
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]